import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const characterNewForm = fs.readFileSync(
  path.join(process.cwd(), 'src/app/characters/new/CharacterNewForm.tsx'),
  'utf8'
)
const statRollRoute = fs.readFileSync(
  path.join(process.cwd(), 'src/app/api/characters/[id]/stat-rolls/route.ts'),
  'utf8'
)
const characterRoute = fs.readFileSync(
  path.join(process.cwd(), 'src/app/api/characters/[id]/route.ts'),
  'utf8'
)

test('rolled ability sets are generated by the server route with crypto randomness', () => {
  assert.match(statRollRoute, /from 'node:crypto'/)
  assert.match(statRollRoute, /randomInt\(1, 7\)/)
  assert.match(statRollRoute, /server-roll-\$\{index \+ 1\}-\$\{randomUUID\(\)\}/)
  assert.match(statRollRoute, /assertCharacterManageableByUser/)
})

test('creation form requests rolled ability sets instead of fabricating them locally', () => {
  assert.doesNotMatch(characterNewForm, /createRolledStatSets/)
  assert.match(characterNewForm, /fetch\(`\/api\/characters\/\$\{id\}\/stat-rolls`/)
  assert.match(characterNewForm, /setRolledStatSets\(json\.rolled_sets \?\? \[\]\)/)
  assert.match(characterNewForm, /const \[rollingStats, setRollingStats\]/)
})

test('non-DM character API responses strip DM-only fields before draft hydration', () => {
  assert.match(characterRoute, /if \(!hasDmAccess\(profile\.role\)\)/)
  assert.match(characterRoute, /delete \(responseCharacter as Partial<typeof responseCharacter>\)\.character_type/)
  assert.match(characterRoute, /delete \(responseCharacter as Partial<typeof responseCharacter>\)\.dm_notes/)
  assert.match(characterNewForm, /const \[characterType, setCharacterType\] = useState<CharacterType \| ''>\(isDm \? 'pc' : ''\)/)
  assert.match(characterNewForm, /if \(isDm\) \{\s+setCharacterType\(data\.character_type \?\? 'pc'\)/)
})
