-- PHB 2014 content pass:
-- add core PHB species, subraces, and Variant Human on top of the lineage model.
--
-- Rows stay compatible with the current single-species picker by keeping
-- subraces and variants as selectable flattened species entries, while the
-- lineage metadata groups them under parent PHB species rows.

INSERT INTO public.species_traits (
  name,
  description,
  source,
  amended,
  amendment_note
)
VALUES
  ('Darkvision', 'You can see in darkness within 60 feet as if it were dim light, and dim light as if it were bright light.', 'PHB', false, NULL),
  ('Dwarven Resilience', 'You have advantage on saves against poison and resistance to poison damage.', 'PHB', false, NULL),
  ('Dwarven Combat Training', 'You are proficient with the battleaxe, handaxe, light hammer, and warhammer.', 'PHB', false, NULL),
  ('Stonecunning', 'You gain doubled proficiency on History checks related to stonework.', 'PHB', false, NULL),
  ('Dwarven Toughness', 'Your hit point maximum increases by 1 per level.', 'PHB', true, 'Persistent per-level hit point bonuses are not yet automated.'),
  ('Dwarven Armor Training', 'You are proficient with light and medium armor.', 'PHB', true, 'Species-granted armor proficiency is not yet surfaced separately from class proficiencies.'),
  ('Keen Senses', 'You are proficient in the Perception skill.', 'PHB', true, 'Species-granted fixed skill proficiencies are not yet surfaced as locked entries in the sheet picker.'),
  ('Fey Ancestry', 'You have advantage on saves against being charmed, and magic cannot put you to sleep.', 'PHB', false, NULL),
  ('Trance', 'You meditate deeply for 4 hours instead of sleeping to gain the benefit of a long rest.', 'PHB', false, NULL),
  ('Elf Weapon Training', 'You are proficient with the longsword, shortsword, shortbow, and longbow.', 'PHB', true, 'Species-granted weapon proficiencies are not yet surfaced separately from class proficiencies.'),
  ('Cantrip', 'You know one cantrip from a specified spell list tied to this lineage.', 'PHB', true, 'Species cantrip choices are not yet modeled as interactive spell options.'),
  ('Extra Language', 'You learn one extra language of your choice.', 'PHB', false, NULL),
  ('Fleet of Foot', 'Your walking speed increases by 5 feet.', 'PHB', false, NULL),
  ('Mask of the Wild', 'You can attempt to hide when lightly obscured by natural phenomena.', 'PHB', true, 'Situational stealth exceptions are not yet automated.'),
  ('Superior Darkvision', 'Your darkvision extends to 120 feet.', 'PHB', false, NULL),
  ('Sunlight Sensitivity', 'You suffer penalties on sight-based attacks and Perception checks in direct sunlight.', 'PHB', true, 'Sunlight sensitivity penalties are not yet automated.'),
  ('Drow Magic', 'You gain innate drow spellcasting as you level.', 'PHB', true, 'Species innate spellcasting is not yet automated.'),
  ('Lucky', 'When you roll a 1 on an attack roll, ability check, or saving throw, you can reroll the die.', 'PHB', true, 'Automatic reroll handling is not yet automated.'),
  ('Brave', 'You have advantage on saving throws against being frightened.', 'PHB', false, NULL),
  ('Halfling Nimbleness', 'You can move through the space of any creature that is larger than you.', 'PHB', true, 'Movement exceptions are not yet automated.'),
  ('Naturally Stealthy', 'You can attempt to hide behind creatures that are at least one size larger than you.', 'PHB', true, 'Situational stealth exceptions are not yet automated.'),
  ('Stout Resilience', 'You have advantage on saves against poison and resistance to poison damage.', 'PHB', false, NULL),
  ('Draconic Ancestry', 'Choose a dragon ancestry that sets your breath weapon and resistance type.', 'PHB', true, 'Dragon ancestry choice is not yet modeled as an interactive species option.'),
  ('Breath Weapon', 'You can exhale destructive energy shaped by your ancestry.', 'PHB', true, 'Breath weapon attacks are not yet automated.'),
  ('Damage Resistance', 'You gain resistance to the damage type tied to your ancestry.', 'PHB', true, 'Ancestry-based resistance choice is not yet modeled as an interactive species option.'),
  ('Gnome Cunning', 'You have advantage on mental saves against magic.', 'PHB', false, NULL),
  ('Natural Illusionist', 'You know the Minor Illusion cantrip.', 'PHB', true, 'Species-granted cantrips are not yet automated.'),
  ('Speak with Small Beasts', 'You can communicate simple ideas with Small or smaller beasts.', 'PHB', false, NULL),
  ('Artificer''s Lore', 'You add doubled proficiency on History checks about magic items, alchemy, or technology.', 'PHB', true, 'Specialized expertise riders are not yet automated.'),
  ('Tinker', 'You can create tiny clockwork devices with tinker''s tools.', 'PHB', true, 'Species crafting side activity is not yet automated.'),
  ('Skill Versatility', 'You gain proficiency in two skills of your choice.', 'PHB', false, NULL),
  ('Menacing', 'You are proficient in the Intimidation skill.', 'PHB', true, 'Species-granted fixed skill proficiencies are not yet surfaced as locked entries in the sheet picker.'),
  ('Relentless Endurance', 'Once per long rest, you can drop to 1 hit point instead of 0.', 'PHB', true, 'Once-per-rest survival riders are not yet automated.'),
  ('Savage Attacks', 'When you score a critical hit with a melee weapon, you roll one extra damage die.', 'PHB', true, 'Critical-hit damage riders are not yet automated.'),
  ('Hellish Resistance', 'You have resistance to fire damage.', 'PHB', false, NULL),
  ('Infernal Legacy', 'You gain innate tiefling spellcasting as you level.', 'PHB', true, 'Species innate spellcasting is not yet automated.'),
  ('Variant Human', 'You gain one feat, one skill proficiency, one extra language, and two +1 ability increases of your choice.', 'PHB', false, NULL)
ON CONFLICT (name, source) DO UPDATE
SET
  description = EXCLUDED.description,
  amended = EXCLUDED.amended,
  amendment_note = EXCLUDED.amendment_note;

INSERT INTO public.species (
  name,
  parent_species_id,
  lineage_key,
  variant_type,
  variant_order,
  size,
  speed,
  ability_score_bonuses,
  languages,
  traits,
  senses,
  damage_resistances,
  condition_immunities,
  source,
  amended,
  amendment_note
)
VALUES
  (
    'Dwarf',
    NULL,
    'dwarf',
    'base',
    0,
    'medium',
    25,
    '[{"ability":"con","bonus":2}]'::jsonb,
    ARRAY['Common', 'Dwarvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Resilience' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Combat Training' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Stonecunning' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY['poison'],
    ARRAY[]::text[],
    'PHB',
    true,
    'Base PHB lineage row. Choose Hill Dwarf or Mountain Dwarf for the complete PHB species package.'
  ),
  (
    'Elf',
    NULL,
    'elf',
    'base',
    0,
    'medium',
    30,
    '[{"ability":"dex","bonus":2}]'::jsonb,
    ARRAY['Common', 'Elvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Keen Senses' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Fey Ancestry' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Trance' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Base PHB lineage row. Choose High Elf, Wood Elf, or Dark Elf (Drow) for the complete PHB species package.'
  ),
  (
    'Halfling',
    NULL,
    'halfling',
    'base',
    0,
    'small',
    25,
    '[{"ability":"dex","bonus":2}]'::jsonb,
    ARRAY['Common', 'Halfling'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Lucky' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Brave' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Halfling Nimbleness' AND source = 'PHB')
    ]::uuid[],
    '[]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Base PHB lineage row. Choose Lightfoot Halfling or Stout Halfling for the complete PHB species package.'
  ),
  (
    'Human',
    NULL,
    'human',
    'base',
    0,
    'medium',
    30,
    '[{"ability":"str","bonus":1},{"ability":"dex","bonus":1},{"ability":"con","bonus":1},{"ability":"int","bonus":1},{"ability":"wis","bonus":1},{"ability":"cha","bonus":1}]'::jsonb,
    ARRAY['Common'],
    ARRAY[]::uuid[],
    '[]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    false,
    NULL
  ),
  (
    'Dragonborn',
    NULL,
    'dragonborn',
    'base',
    0,
    'medium',
    30,
    '[{"ability":"str","bonus":2},{"ability":"cha","bonus":1}]'::jsonb,
    ARRAY['Common', 'Draconic'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Draconic Ancestry' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Breath Weapon' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Damage Resistance' AND source = 'PHB')
    ]::uuid[],
    '[]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Draconic ancestry, breath weapon, and resistance type choices are not yet modeled as interactive species options.'
  ),
  (
    'Gnome',
    NULL,
    'gnome',
    'base',
    0,
    'small',
    25,
    '[{"ability":"int","bonus":2}]'::jsonb,
    ARRAY['Common', 'Gnomish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Gnome Cunning' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Base PHB lineage row. Choose Forest Gnome or Rock Gnome for the complete PHB species package.'
  ),
  (
    'Half-Elf',
    NULL,
    'half_elf',
    'base',
    0,
    'medium',
    30,
    '[{"ability":"cha","bonus":2}]'::jsonb,
    ARRAY['Common', 'Elvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Fey Ancestry' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Skill Versatility' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    false,
    NULL
  ),
  (
    'Half-Orc',
    NULL,
    'half_orc',
    'base',
    0,
    'medium',
    30,
    '[{"ability":"str","bonus":2},{"ability":"con","bonus":1}]'::jsonb,
    ARRAY['Common', 'Orc'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Menacing' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Relentless Endurance' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Savage Attacks' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Fixed half-orc features are seeded, but species-granted Intimidation is not yet surfaced as a locked sheet proficiency.'
  ),
  (
    'Tiefling',
    NULL,
    'tiefling',
    'base',
    0,
    'medium',
    30,
    '[{"ability":"int","bonus":1},{"ability":"cha","bonus":2}]'::jsonb,
    ARRAY['Common', 'Infernal'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Hellish Resistance' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Infernal Legacy' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY['fire'],
    ARRAY[]::text[],
    'PHB',
    true,
    'Innate tiefling spellcasting is not yet automated.'
  )
ON CONFLICT (name, source) DO UPDATE
SET
  parent_species_id = EXCLUDED.parent_species_id,
  lineage_key = EXCLUDED.lineage_key,
  variant_type = EXCLUDED.variant_type,
  variant_order = EXCLUDED.variant_order,
  size = EXCLUDED.size,
  speed = EXCLUDED.speed,
  ability_score_bonuses = EXCLUDED.ability_score_bonuses,
  languages = EXCLUDED.languages,
  traits = EXCLUDED.traits,
  senses = EXCLUDED.senses,
  damage_resistances = EXCLUDED.damage_resistances,
  condition_immunities = EXCLUDED.condition_immunities,
  amended = EXCLUDED.amended,
  amendment_note = EXCLUDED.amendment_note;

INSERT INTO public.species (
  name,
  parent_species_id,
  lineage_key,
  variant_type,
  variant_order,
  size,
  speed,
  ability_score_bonuses,
  languages,
  traits,
  senses,
  damage_resistances,
  condition_immunities,
  source,
  amended,
  amendment_note
)
VALUES
  (
    'Hill Dwarf',
    (SELECT id FROM public.species WHERE name = 'Dwarf' AND source = 'PHB'),
    'dwarf',
    'subrace',
    1,
    'medium',
    25,
    '[{"ability":"con","bonus":2},{"ability":"wis","bonus":1}]'::jsonb,
    ARRAY['Common', 'Dwarvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Resilience' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Combat Training' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Stonecunning' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Toughness' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY['poison'],
    ARRAY[]::text[],
    'PHB',
    true,
    'Per-level hit point increases from Dwarven Toughness are not yet automated.'
  ),
  (
    'Mountain Dwarf',
    (SELECT id FROM public.species WHERE name = 'Dwarf' AND source = 'PHB'),
    'dwarf',
    'subrace',
    2,
    'medium',
    25,
    '[{"ability":"con","bonus":2},{"ability":"str","bonus":2}]'::jsonb,
    ARRAY['Common', 'Dwarvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Resilience' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Combat Training' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Stonecunning' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Dwarven Armor Training' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY['poison'],
    ARRAY[]::text[],
    'PHB',
    true,
    'Mountain dwarf armor proficiency is not yet surfaced separately from class proficiencies.'
  ),
  (
    'High Elf',
    (SELECT id FROM public.species WHERE name = 'Elf' AND source = 'PHB'),
    'elf',
    'subrace',
    1,
    'medium',
    30,
    '[{"ability":"dex","bonus":2},{"ability":"int","bonus":1}]'::jsonb,
    ARRAY['Common', 'Elvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Keen Senses' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Fey Ancestry' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Trance' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Elf Weapon Training' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Cantrip' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Extra Language' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'The bonus wizard cantrip choice is not yet modeled as a species spell option.'
  ),
  (
    'Wood Elf',
    (SELECT id FROM public.species WHERE name = 'Elf' AND source = 'PHB'),
    'elf',
    'subrace',
    2,
    'medium',
    35,
    '[{"ability":"dex","bonus":2},{"ability":"wis","bonus":1}]'::jsonb,
    ARRAY['Common', 'Elvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Keen Senses' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Fey Ancestry' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Trance' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Elf Weapon Training' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Fleet of Foot' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Mask of the Wild' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Mask of the Wild hiding exceptions are not yet automated.'
  ),
  (
    'Dark Elf (Drow)',
    (SELECT id FROM public.species WHERE name = 'Elf' AND source = 'PHB'),
    'elf',
    'subrace',
    3,
    'medium',
    30,
    '[{"ability":"dex","bonus":2},{"ability":"cha","bonus":1}]'::jsonb,
    ARRAY['Common', 'Elvish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Superior Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Keen Senses' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Fey Ancestry' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Trance' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Sunlight Sensitivity' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Drow Magic' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Elf Weapon Training' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":120}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Innate drow spellcasting and sunlight sensitivity penalties are not yet automated.'
  ),
  (
    'Lightfoot Halfling',
    (SELECT id FROM public.species WHERE name = 'Halfling' AND source = 'PHB'),
    'halfling',
    'subrace',
    1,
    'small',
    25,
    '[{"ability":"dex","bonus":2},{"ability":"cha","bonus":1}]'::jsonb,
    ARRAY['Common', 'Halfling'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Lucky' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Brave' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Halfling Nimbleness' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Naturally Stealthy' AND source = 'PHB')
    ]::uuid[],
    '[]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Naturally Stealthy hiding exceptions are not yet automated.'
  ),
  (
    'Stout Halfling',
    (SELECT id FROM public.species WHERE name = 'Halfling' AND source = 'PHB'),
    'halfling',
    'subrace',
    2,
    'small',
    25,
    '[{"ability":"dex","bonus":2},{"ability":"con","bonus":1}]'::jsonb,
    ARRAY['Common', 'Halfling'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Lucky' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Brave' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Halfling Nimbleness' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Stout Resilience' AND source = 'PHB')
    ]::uuid[],
    '[]'::jsonb,
    ARRAY['poison'],
    ARRAY[]::text[],
    'PHB',
    false,
    NULL
  ),
  (
    'Forest Gnome',
    (SELECT id FROM public.species WHERE name = 'Gnome' AND source = 'PHB'),
    'gnome',
    'subrace',
    1,
    'small',
    25,
    '[{"ability":"int","bonus":2},{"ability":"dex","bonus":1}]'::jsonb,
    ARRAY['Common', 'Gnomish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Gnome Cunning' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Natural Illusionist' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Speak with Small Beasts' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'The Minor Illusion cantrip grant is not yet automated.'
  ),
  (
    'Rock Gnome',
    (SELECT id FROM public.species WHERE name = 'Gnome' AND source = 'PHB'),
    'gnome',
    'subrace',
    2,
    'small',
    25,
    '[{"ability":"int","bonus":2},{"ability":"con","bonus":1}]'::jsonb,
    ARRAY['Common', 'Gnomish'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Darkvision' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Gnome Cunning' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Artificer''s Lore' AND source = 'PHB'),
      (SELECT id FROM public.species_traits WHERE name = 'Tinker' AND source = 'PHB')
    ]::uuid[],
    '[{"type":"darkvision","range_ft":60}]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    true,
    'Rock gnome tinkering is not yet automated.'
  ),
  (
    'Variant Human',
    (SELECT id FROM public.species WHERE name = 'Human' AND source = 'PHB'),
    'human',
    'variant',
    1,
    'medium',
    30,
    '[]'::jsonb,
    ARRAY['Common'],
    ARRAY[
      (SELECT id FROM public.species_traits WHERE name = 'Variant Human' AND source = 'PHB')
    ]::uuid[],
    '[]'::jsonb,
    ARRAY[]::text[],
    ARRAY[]::text[],
    'PHB',
    false,
    NULL
  )
ON CONFLICT (name, source) DO UPDATE
SET
  parent_species_id = EXCLUDED.parent_species_id,
  lineage_key = EXCLUDED.lineage_key,
  variant_type = EXCLUDED.variant_type,
  variant_order = EXCLUDED.variant_order,
  size = EXCLUDED.size,
  speed = EXCLUDED.speed,
  ability_score_bonuses = EXCLUDED.ability_score_bonuses,
  languages = EXCLUDED.languages,
  traits = EXCLUDED.traits,
  senses = EXCLUDED.senses,
  damage_resistances = EXCLUDED.damage_resistances,
  condition_immunities = EXCLUDED.condition_immunities,
  amended = EXCLUDED.amended,
  amendment_note = EXCLUDED.amendment_note;
