-- Batch 3k: concrete catalog rows needed to resolve PHB starting-equipment
-- helper choices into durable character_equipment_items rows.

INSERT INTO public.equipment_items (
  key,
  name,
  item_category,
  cost_quantity,
  cost_unit,
  weight_lb,
  source,
  amended,
  amendment_note
)
VALUES
  ('arrows', 'Arrows', 'gear', 1, 'gp', 1.00, 'PHB', false, NULL),
  ('crossbow_bolts', 'Crossbow Bolts', 'gear', 1, 'gp', 1.50, 'PHB', false, NULL),
  ('crystal_arcane_focus', 'Crystal (Arcane Focus)', 'gear', 10, 'gp', 1.00, 'PHB', false, NULL),
  ('orb_arcane_focus', 'Orb (Arcane Focus)', 'gear', 20, 'gp', 3.00, 'PHB', false, NULL),
  ('rod_arcane_focus', 'Rod (Arcane Focus)', 'gear', 10, 'gp', 2.00, 'PHB', false, NULL),
  ('staff_arcane_focus', 'Staff (Arcane Focus)', 'gear', 5, 'gp', 4.00, 'PHB', false, NULL),
  ('wand_arcane_focus', 'Wand (Arcane Focus)', 'gear', 10, 'gp', 1.00, 'PHB', false, NULL),
  ('sprig_of_mistletoe', 'Sprig of Mistletoe', 'gear', 1, 'gp', 0.00, 'PHB', false, NULL),
  ('totem_druidic_focus', 'Totem (Druidic Focus)', 'gear', 1, 'gp', 0.00, 'PHB', false, NULL),
  ('wooden_staff_druidic_focus', 'Wooden Staff (Druidic Focus)', 'gear', 5, 'gp', 4.00, 'PHB', false, NULL),
  ('yew_wand_druidic_focus', 'Yew Wand (Druidic Focus)', 'gear', 10, 'gp', 1.00, 'PHB', false, NULL),
  ('alchemists_supplies', 'Alchemist''s Supplies', 'gear', 50, 'gp', 8.00, 'PHB', false, NULL),
  ('brewers_supplies', 'Brewer''s Supplies', 'gear', 20, 'gp', 9.00, 'PHB', false, NULL),
  ('calligraphers_supplies', 'Calligrapher''s Supplies', 'gear', 10, 'gp', 5.00, 'PHB', false, NULL),
  ('carpenters_tools', 'Carpenter''s Tools', 'gear', 8, 'gp', 6.00, 'PHB', false, NULL),
  ('cobblers_tools', 'Cobbler''s Tools', 'gear', 5, 'gp', 5.00, 'PHB', false, NULL),
  ('cooks_utensils', 'Cook''s Utensils', 'gear', 1, 'gp', 8.00, 'PHB', false, NULL),
  ('glassblowers_tools', 'Glassblower''s Tools', 'gear', 30, 'gp', 5.00, 'PHB', false, NULL),
  ('jewelers_tools', 'Jeweler''s Tools', 'gear', 25, 'gp', 2.00, 'PHB', false, NULL),
  ('leatherworkers_tools', 'Leatherworker''s Tools', 'gear', 5, 'gp', 5.00, 'PHB', false, NULL),
  ('masons_tools', 'Mason''s Tools', 'gear', 10, 'gp', 8.00, 'PHB', false, NULL),
  ('painters_supplies', 'Painter''s Supplies', 'gear', 10, 'gp', 5.00, 'PHB', false, NULL),
  ('potters_tools', 'Potter''s Tools', 'gear', 10, 'gp', 3.00, 'PHB', false, NULL),
  ('smiths_tools', 'Smith''s Tools', 'gear', 20, 'gp', 8.00, 'PHB', false, NULL),
  ('tinkers_tools', 'Tinker''s Tools', 'gear', 50, 'gp', 10.00, 'PHB', false, NULL),
  ('weavers_tools', 'Weaver''s Tools', 'gear', 1, 'gp', 5.00, 'PHB', false, NULL),
  ('woodcarvers_tools', 'Woodcarver''s Tools', 'gear', 1, 'gp', 5.00, 'PHB', false, NULL),
  ('forgery_kit', 'Forgery Kit', 'gear', 15, 'gp', 5.00, 'PHB', false, NULL),
  ('dice_set', 'Dice Set', 'gear', 1, 'sp', 0.00, 'PHB', false, NULL),
  ('playing_card_set', 'Playing Card Set', 'gear', 5, 'sp', 0.00, 'PHB', false, NULL),
  ('bagpipes', 'Bagpipes', 'gear', 30, 'gp', 6.00, 'PHB', false, NULL),
  ('drum', 'Drum', 'gear', 6, 'gp', 3.00, 'PHB', false, NULL),
  ('dulcimer', 'Dulcimer', 'gear', 25, 'gp', 10.00, 'PHB', false, NULL),
  ('flute', 'Flute', 'gear', 2, 'gp', 1.00, 'PHB', false, NULL),
  ('horn', 'Horn', 'gear', 3, 'gp', 2.00, 'PHB', false, NULL),
  ('lute', 'Lute', 'gear', 35, 'gp', 2.00, 'PHB', false, NULL),
  ('lyre', 'Lyre', 'gear', 30, 'gp', 2.00, 'PHB', false, NULL),
  ('pan_flute', 'Pan Flute', 'gear', 12, 'gp', 2.00, 'PHB', false, NULL),
  ('shawm', 'Shawm', 'gear', 2, 'gp', 1.00, 'PHB', false, NULL),
  ('viol', 'Viol', 'gear', 30, 'gp', 1.00, 'PHB', false, NULL),
  ('weighted_dice', 'Weighted Dice', 'gear', 1, 'sp', 0.00, 'PHB', false, NULL),
  ('marked_cards', 'Deck of Marked Cards', 'gear', 5, 'sp', 0.00, 'PHB', false, NULL),
  ('fake_signet_ring', 'Fake Signet Ring', 'gear', 5, 'gp', 0.00, 'PHB', false, NULL)
ON CONFLICT (key) DO UPDATE
SET
  name = EXCLUDED.name,
  item_category = EXCLUDED.item_category,
  cost_quantity = EXCLUDED.cost_quantity,
  cost_unit = EXCLUDED.cost_unit,
  weight_lb = EXCLUDED.weight_lb,
  source = EXCLUDED.source,
  amended = EXCLUDED.amended,
  amendment_note = EXCLUDED.amendment_note;
